---
name: 📖 Documentation Enhancement
description: Suggest an enhancement, addition, or modification to the NetBox plugin documentation.
labels: [ "type: docs" ]
assignees: "kprince28"
body:
  - type: dropdown
    attributes:
      label: Change Type
      description: Specify the nature of your documentation change.
      options:
        - Addition
        - Correction
        - Removal
        - Cleanup (formatting, typos, etc.)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Documentation Section
      description: Indicate the section of the documentation that this change primarily affects.
      options:
        - Installation Instructions
        - Configuration Parameters
        - Functionality/Features
        - Administration/Development
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Changes
      description: Please describe the proposed changes and explain their significance or necessity.
    validations:
      required: true
