# Generated by Django 4.1.4 on 2022-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=50)),
                ('type', models.CharField(default='device-types', max_length=20)),
                ('sha', models.CharField(max_length=40)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('imported_dt', models.IntegerField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
            ],
        ),
    ]
