# Generated by Django 5.2.5 on 2025-09-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_metatype_importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatype',
            options={'ordering': ['name']},
        ),
    ]
