name: Changelog Generator

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  build:
    name: "Changelog Generator"
    runs-on: ubuntu-latest
    if: github.ref_protected != 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Generate changelog"
        id: changelog
        uses: charmixer/auto-changelog-action@v1.4
        with:
          exclude_labels: "status: abandoned,type: duplicate,type: question,type: wontfix,type: invalid"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push to dev
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: "CHANGELOG.md"
          message: "[skip ci] Updated CHANGELOG.md"
          new_branch: dev
          push: origin dev --set-upstream
          committer_name: GitHub Actions
          committer_email: actions@github.com
          default_author: github_actions
